### PR TITLE
Update Havana references to Icehouse

### PR DESCRIPTION
**Pull request by verdurin**
Please consider including this on a new Icehouse branch

### CODE REVIEW

**Comment by alvarolopez** [comment]
:+1:

**Comment by spinto** [comment]
I wanted actually to propose this myself :). Is the current stable havana release working on icehouse, did somebody test it?

**Comment by bhagemeier** [comment]
On 01.08.2014 14:32, Salvatore Pinto wrote :

> I wanted actually to propose this myself :). Is the current stable
> havana release working on icehouse, did somebody test it?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/EGI-FCTF/occi-os/pull/3#issuecomment-50878716.
> 
> Hi Álvaro,

we upgraded to Icehouse this week and are running the master branch on 
it. Depending on the repository you look at, this is identical to or not 
far from stable/havana. So I'd say yes it is working, but haven't given 
it an overall test of all features.

Cheers,
Björn

## 

Dipl.-Inform. Björn Hagemeier
Federated Systems and Data
Juelich Supercomputing Centre
Institute for Advanced Simulation

Phone: +49 2461 61 1584
Fax  : +49 2461 61 6656
Email: b.hagemeier@fz-juelich.de
Skype: bhagemeier
WWW  : http://www.fz-juelich.de/jsc

JSC is the coordinator of the
John von Neumann Institute for Computing
and member of the
Gauss Centre for Supercomputing

---

---

Forschungszentrum Juelich GmbH
52425 Juelich
Sitz der Gesellschaft: Juelich
Eingetragen im Handelsregister des Amtsgerichts Dueren Nr. HR B 3498
Vorsitzender des Aufsichtsrats: MinDir Dr. Karl Eugen Huthmacher
Geschaeftsfuehrung: Prof. Dr.-Ing. Wolfgang Marquardt (Vorsitzender),
Karsten Beneke (stellv. Vorsitzender), Prof. Dr.-Ing. Harald Bolt,

## Prof. Dr. Sebastian M. Schmidt

---

**Comment by verdurin** [comment]
It's mostly working for us, though as with Björn I haven't tested it exhaustively yet. This is our first attempt so there may well be other things wrong, anyway.

**Pull request merged**
